input {
  tcp {
    port => 5045
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["http://host.docker.internal:9200"]
    index => "user-service-v2-logs-%{+yyyy.MM.dd}"
  }
  stdout { codec => rubydebug }
}