# Server
server.port=8090
spring.application.name=DOCKER-DEMO
server.servlet.context-path=/demo

# Redis - Windows (host.docker.internal = Windows host from inside container)
spring.data.redis.host=host.docker.internal
spring.data.redis.port=6379
spring.cache.type=redis

# Elasticsearch - Windows
spring.elasticsearch.uris=http://host.docker.internal:9200